import { defineConfig, devices } from '@playwright/test';

/**
 * End-to-end tests run against the *production build*, not the dev server.
 *
 * The service worker is only generated by `vite build`, and two of the specs assert
 * offline behaviour and the web manifest — neither of which exists under `vite dev`
 * with `devOptions.enabled: false`.
 */
export default defineConfig({
	testDir: 'e2e',
	testMatch: '**/*.e2e.ts',
	fullyParallel: true,
	forbidOnly: !!process.env.CI,
	retries: process.env.CI ? 2 : 0,
	reporter: process.env.CI ? 'list' : [['list']],
	use: {
		baseURL: 'http://localhost:4173',
		trace: 'on-first-retry'
	},
	projects: [
		{
			name: 'chromium',
			use: { ...devices['Desktop Chrome'] }
		}
	],
	webServer: {
		/*
		 * The real Worker, not `vite preview`.
		 *
		 * Half of what these specs exercise now — sessions, sync, the D1 constraints that
		 * enforce one next action per project — only exists behind the Worker. A static
		 * preview would pass every test that does not matter and none that do.
		 */
		command:
			'npm run build && npx wrangler d1 migrations apply cairn --local && npx wrangler pages dev --port 4173',
		port: 4173,
		/*
		 * Never reuse. Reusing meant Playwright skipped the build and pointed a fresh
		 * suite at whatever an older `vite preview` still had open — which fails as a wall
		 * of 404s on chunk hashes that no longer exist, and looks like the app is broken
		 * rather than the server being stale. The build takes about a second.
		 */
		reuseExistingServer: false,
		timeout: 120_000
	}
});
