import { defineConfig, devices } from '@playwright/test';

/**
 * End-to-end tests run against the *production build*, not the dev server.
 *
 * The service worker is only generated by `vite build`, and two of the specs assert
 * offline behaviour and the web manifest — neither of which exists under `vite dev`
 * with `devOptions.enabled: false`.
 */
export default defineConfig({
	testDir: 'e2e',
	testMatch: '**/*.e2e.ts',
	fullyParallel: true,
	forbidOnly: !!process.env.CI,
	retries: process.env.CI ? 2 : 0,
	reporter: process.env.CI ? 'list' : [['list']],
	use: {
		baseURL: 'http://localhost:4173',
		trace: 'on-first-retry'
	},
	projects: [
		{
			name: 'chromium',
			use: { ...devices['Desktop Chrome'] }
		}
	],
	webServer: {
		command: 'npm run build && npm run preview -- --port 4173 --strictPort',
		port: 4173,
		reuseExistingServer: !process.env.CI,
		timeout: 120_000
	}
});
